# Prometheus configuration for Slonana Validator monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'slonana-validators'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Slonana Validator metrics
  - job_name: 'slonana-validator'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Additional validator instances (add as needed)
  - job_name: 'slonana-cluster'
    static_configs:
      - targets: 
          # Add other validator instances here
          # - 'validator1.example.com:9090'
          # - 'validator2.example.com:9090'
    metrics_path: '/metrics'
    scrape_interval: 10s
